#!/bin/bash

echo "🚀 Starting SUPER PRODUCT REPAIR SCRIPT V2..."

# 1. Discover Postgres Container
POSTGRES_CONTAINER=$(docker ps --format '{{.Names}}' | grep "postgres" | head -n 1)
if [ -z "$POSTGRES_CONTAINER" ]; then
    echo "❌ Error: Postgres container not found."
    exit 1
fi

# 2. Advanced Database Fix
echo "🗄️  1. Patching Database Schema..."
SQL_FIX=$(cat <<EOF
-- Fix Product Table ID generation
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='product' AND column_name='available') THEN
        ALTER TABLE product ADD COLUMN available BOOLEAN DEFAULT TRUE;
        UPDATE product SET available = TRUE;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='product' AND column_name='image_url') THEN
        ALTER TABLE product ADD COLUMN image_url VARCHAR(255);
    END IF;

    -- Ensure 'id' is an identity column
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='product' AND column_name='id' AND is_identity='YES') THEN
        BEGIN
            ALTER TABLE product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        EXCEPTION WHEN OTHERS THEN
            CREATE SEQUENCE IF NOT EXISTS product_id_seq;
            ALTER TABLE product ALTER COLUMN id SET DEFAULT nextval('product_id_seq');
            PERFORM setval('product_id_seq', coalesce(max(id), 1)) FROM product;
        END;
    END IF;
END \$\$;

SELECT setval(pg_get_serial_sequence('product', 'id'), coalesce(max(id), 1)) FROM product;
SELECT setval(pg_get_serial_sequence('clients', 'id'), coalesce(max(id), 1)) FROM clients;
SELECT setval(pg_get_serial_sequence('orders', 'id'), coalesce(max(id), 1)) FROM orders;
EOF
)
docker exec -i "$POSTGRES_CONTAINER" psql -U postgres -d ecommerce -c "$SQL_FIX"

# 3. Patching Java Logic
echo "📝 2. Patching Java Files..."
PROD_BASE="product-service/product-service/src/main/java/com/ecommerce/product/service"
cat <<EOF > "$PROD_BASE/controller/ProductController.java"
package com.ecommerce.product.service.controller;

import com.ecommerce.product.service.model.Product;
import com.ecommerce.product.service.service.ProductService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/products")
@CrossOrigin(origins = "*")
public class ProductController {

    private final ProductService productService;

    public ProductController(ProductService productService) {
        this.productService = productService;
    }

    @GetMapping
    public List<Product> getAllProducts() {
        return productService.getAllProducts();
    }

    @GetMapping("/{id}")
    public ResponseEntity<Product> getProductById(@PathVariable Long id) {
        return productService.getProductById(id)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    @PostMapping
    public ResponseEntity<?> createProduct(@RequestBody Product product) {
        try {
            System.out.println("📥 Receiving Product: " + product);
            product.setAvailable(true); 
            Product saved = productService.createProduct(product);
            return ResponseEntity.status(HttpStatus.CREATED).body(saved);
        } catch (Exception e) {
            System.err.println("❌ Error saving product: " + e.getMessage());
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body("Error: " + e.getMessage());
        }
    }

    @PutMapping("/{id}")
    public ResponseEntity<?> updateProduct(@PathVariable Long id, @RequestBody Product product) {
        try {
            return productService.updateProduct(id, product)
                    .map(ResponseEntity::ok)
                    .orElse(ResponseEntity.notFound().build());
        } catch (Exception e) {
            System.err.println("❌ Error updating product: " + e.getMessage());
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body("Error: " + e.getMessage());
        }
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteProduct(@PathVariable Long id) {
        productService.deleteProduct(id);
        return ResponseEntity.noContent().build();
    }

    @PostMapping("/{id}/reduce-stock")
    public ResponseEntity<Void> reduceStock(@PathVariable Long id, @RequestParam int quantity) {
        productService.reduceStock(id, quantity);
        return ResponseEntity.ok().build();
    }
}
EOF

# 4. Universal Uppercase Sync (Matches Eureka)
echo "🔡 3. Ensuring Everything is Uppercase (Eureka Standard)..."
# We exclude docker-compose.yml from being lower-to-upper converted to keep service names as defined
find . -type f \( -name "*.java" -o -name "*.yml" -o -name "*.properties" \) ! -name "docker-compose.yml" | xargs sed -i 's/product-service/PRODUCT-SERVICE/g' 2>/dev/null
find . -type f \( -name "*.java" -o -name "*.yml" -o -name "*.properties" \) ! -name "docker-compose.yml" | xargs sed -i 's/order-service/ORDER-SERVICE/g' 2>/dev/null
find . -type f \( -name "*.java" -o -name "*.yml" -o -name "*.properties" \) ! -name "docker-compose.yml" | xargs sed -i 's/client-service/CLIENT-SERVICE/g' 2>/dev/null
find . -type f \( -name "*.java" -o -name "*.yml" -o -name "*.properties" \) ! -name "docker-compose.yml" | xargs sed -i 's/payment-service/PAYMENT-SERVICE/g' 2>/dev/null

# 5. Fix potentially renamed services in docker-compose.yml if they were already renamed
if grep -q "PRODUCT-SERVICE:" docker-compose.yml; then
    echo "🩹 Reverting service names in docker-compose.yml back to lowercase..."
    sed -i 's/PRODUCT-SERVICE:/product-service:/g' docker-compose.yml
    sed -i 's/ORDER-SERVICE:/order-service:/g' docker-compose.yml
    sed -i 's/CLIENT-SERVICE:/client-service:/g' docker-compose.yml
    sed -i 's/PAYMENT-SERVICE:/payment-service:/g' docker-compose.yml
    sed -i 's/API-GATEWAY:/api-gateway:/g' docker-compose.yml
fi

# 6. Rebuild & Restart
echo "🛠️  4. Rebuilding Services..."
docker-compose up -d --build product-service api-gateway order-service

echo "✨ DONE! Tell her to wait 1 minute, then check the dashboard."
